name: Test SSH Setup

on:
  workflow_dispatch:

jobs:
  test-ssh-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan example.com >> /home/runner/.ssh/known_hosts
          echo "key asdf" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions

      - name: Check generated files
        run: |
          ls -l /home/runner/.ssh/
          cat /home/runner/.ssh/github_actions
