on:
  push:
    # For the develop branch only.
    branches:
      - main

jobs:
  deploy-to-test-server-for-reveiw:
    runs-on: ubuntu-latest
    environment: alt-client-review

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Env
        run: |
          source .env
          echo "${{env.TEST_ENV}}"
