on:
  push:
    # For the develop branch only.
    branches:
      - main

jobs:
  deploy-to-test-server-for-reveiw:
    runs-on: ubuntu-latest
    environment: alt-client-review

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Env
        run: |
          source src/.env
          echo "$TEST_ENV"

      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: src

      - name: Some other action
        run: |
          echo "Variable 1: ${{ env.TEST_ENV }}"
