on:
  push:
    # For the develop branch only.
    branches:
      - main

jobs:
  deploy-to-test-server-for-reveiw:
    runs-on: ubuntu-latest
    environment: alt-client-review

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Echo head ref
        run: |
          echo "test 2 ${{ github.sha }} | ${{ github.workflow_sha }}"
