name: Test SSH Setup

on:
  workflow_dispatch:

jobs:
  test-ssh-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Install and setup SSH keys
        env:
          SSH_PRIVATE_KEY: FAKE_PRIVATE_KEY_CONTENT
          SSH_HOST: example.com
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "FAKE_PRIVATE_KEY_CONTENT" > ~/.ssh/id_rsa
          ssh-keyscan -H "example.com" > ~/.ssh/known_hosts

      # Шаг 3: Проверка результата
      - name: Check generated files
        run: |
          ls -l ~/.ssh/
          cat ~/.ssh/id_rsa
          cat ~/.ssh/known_hosts
