name: Test github head ref

on:
  push:
    branches:
      - 'test/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Echo
        run: echo "${github.ref_name} test 1"
